spring.application.name=Demo105_Exception

spring.datasource.url=jdbc:mysql://localhost:3306/railway91_exception?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

